#!/usr/bin/env perl

use strict;
use warnings;

my $d = int shift;

my @bits = split('', unpack('B64', pack('Q>', $d)));

while (@bits) {
    for (1 .. 4) {
        print shift(@bits);
    }
    print ' ';
}

print "\n";

my $n = 64;

while ($n) {
    $n -= 4;
    printf("%4s ", '^');
}
print "\n";

$n = 64;

while ($n) {
    $n -= 4;
    printf("%4d ", $n + 1);
}
print "\n";
